#!/bin/bash

# Path to aesdsocket binary
AESDSOCKET_BIN="/usr/bin/aesdsocket"

# PID file for the daemon
PIDFILE="/var/run/aesdsocket.pid"

# Function to start the daemon
start_daemon() {
    echo "Starting aesdsocket..."
    start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE \
                      --exec $AESDSOCKET_BIN -- -d
}

# Function to stop the daemon
stop_daemon() {
    echo "Stopping aesdsocket..."
    start-stop-daemon --stop --pidfile $PIDFILE --signal SIGTERM
}

if [ $# -eq 0 ]; then
    start_daemon
fi

trap stop_daemon INT

# Wait for the daemon to exit
wait

